#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(main|staging)"

echo -e "\n🚀 Pushing to remote $BRANCH branch..."

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR." && exit 1
fi

exit 0
